# Generated by Django 6.0.2 on 2026-02-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new_app.contractor'),
        ),
    ]
