# Generated by Django 6.0.2 on 2026-02-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_alter_postjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.contractor'),
        ),
    ]
