# Generated by Django 6.0.2 on 2026-02-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_alter_postjob_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='User',
            new_name='contractor',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='User',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='User',
        ),
        migrations.AddField(
            model_name='contractor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
